### ISSUE TITLE
user-can-see-their-car

### ISSUE THREAD

**Issue by dannyandreev** [dannyandreev/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [ ] Create car object
- [ ] Create background
- [ ] Create HTML car
- [ ] Display car on background
