### ISSUE TITLE
user-can-start-their-car

### ISSUE THREAD

**Issue by dannyandreev** [dannyandreev/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [ ] listen for keydown.code=== 'space'
- [ ] switch car.state from on <=> off every time space is hit
- [ ] create function moveCar(distance)  
- [ ] moveCar(distance) should update car.position based on 'distance' in the direction of car.angle
- [ ] moveCar then needs to redisplay car
- [ ]  make sure that moveCar cannot set position outside of window
- [ ] create a timeout that triggers at 60hz
- [ ] timeout should check if car.state === 'on' if so call moveCar(10px)
- [ ] stop timeout every time car.state === off
- [ ] start timeout every time car.state === on
